#!/bin/bash
# deploy-standard PreToolUse hook
# Blocks agent actions that violate Kyle Deploy Standard v1.
#
# Blocked patterns:
#   1. Write/Edit to /opt/<project>/current/*
#   2. Write/Edit to /etc/systemd/system/*
#   3. Bash `cp ... /opt/<project>/current` or .../releases
#   4. Bash `docker compose up` outside /opt/*/current AND without DEPLOY_RUNNING=1
#
# Protocol: on block, emit JSON {"decision":"block","reason":"..."} on stdout and exit 0,
# OR exit 2 with message on stderr. We use the JSON form for clarity and portability.
# On any internal error, fail OPEN (exit 0 with no decision) so the hook never breaks work.

set +e  # never let set -e kill us — we want fail-open behavior

# ----- helpers -----
emit_block() {
  # $1 = reason (single-line, will be JSON-escaped)
  local reason="$1"
  # Escape for JSON: replace backslash, double-quote, newline
  local escaped
  escaped=$(printf '%s' "$reason" \
    | sed 's/\\/\\\\/g; s/"/\\"/g' \
    | awk 'BEGIN{ORS="\\n"} {print}' \
    | sed 's/\\n$//')
  printf '{"decision":"block","reason":"%s"}\n' "$escaped"
  exit 0
}

allow() {
  exit 0
}

# ----- read input -----
INPUT=$(cat 2>/dev/null || true)
if [ -z "$INPUT" ]; then
  allow
fi

# Extract fields with jq; if jq missing or input isn't JSON, allow.
if ! command -v jq >/dev/null 2>&1; then
  allow
fi

TOOL_NAME=$(printf '%s' "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null)
if [ -z "$TOOL_NAME" ]; then
  allow
fi

# ----- Write / Edit path guards -----
case "$TOOL_NAME" in
  Write|Edit|MultiEdit)
    FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
    if [ -z "$FILE_PATH" ]; then
      allow
    fi

    # Block writes into /opt/<anything>/current/...
    if [[ "$FILE_PATH" =~ ^/opt/[^/]+/current(/|$) ]]; then
      emit_block "Writing to \`${FILE_PATH}\` is blocked by Deploy Standard v1. \`/opt/<project>/current/\` is root-owned and the active release — never edit in place. Commit your change to the project repo, then run \`deploy <project> <env>\`. See the \`deploy-standard\` skill (spec: ~/projects/kyle-dev-infra/docs/deploy-standard.md)."
    fi

    # Block writes into /opt/<anything>/releases/...
    if [[ "$FILE_PATH" =~ ^/opt/[^/]+/releases(/|$) ]]; then
      emit_block "Writing to \`${FILE_PATH}\` is blocked by Deploy Standard v1. \`/opt/<project>/releases/\` is deploy-tool-owned (ephemerality contract). Commit your change to the repo, then run \`deploy <project> <env>\`. See the \`deploy-standard\` skill."
    fi

    # Block hand-written systemd units
    if [[ "$FILE_PATH" =~ ^/etc/systemd/system/ ]]; then
      emit_block "Hand-writing systemd units at \`${FILE_PATH}\` is blocked by Deploy Standard v1. Deployed services must use the template generated by \`deploy init <project>\` (correct \`After=tailscaled.service remote-fs.target\`, \`RequiresMountsFor=\`, \`Type=oneshot RemainAfterExit=true\`). Hand-written units break on reboot. See the \`deploy-standard\` skill."
    fi

    allow
    ;;

  Bash)
    # Bypass: the deploy CLI itself sets DEPLOY_RUNNING=1 before invoking docker/systemd commands.
    # We check the *command* field for explicit DEPLOY_RUNNING=1 prefix (the env var is not
    # visible to the hook process through stdin, but agents who run sub-`deploy` invocations
    # will not trip these guards because the hook only sees the outer Bash command.)
    COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)
    if [ -z "$COMMAND" ]; then
      allow
    fi

    # Fast bypass: explicit marker in the command
    if [[ "$COMMAND" == *"DEPLOY_RUNNING=1"* ]]; then
      allow
    fi

    # Bypass: command is the deploy CLI itself
    if [[ "$COMMAND" =~ (^|[^a-zA-Z0-9_/])deploy([[:space:]]+(init|rollback|status|list|logs|doctor|[a-zA-Z0-9_-]+)) ]]; then
      # Looks like `deploy <subcommand>` — allow (the deploy CLI is the trusted entrypoint)
      allow
    fi

    # --- Block: cp into /opt/<project>/current or /releases ---
    # Match both literal `cp` and `sudo cp`, single-line or chained.
    if [[ "$COMMAND" =~ (^|[^a-zA-Z0-9_])cp[[:space:]]+.*[[:space:]]+/opt/[^[:space:]]+/(current|releases)(/|[[:space:]]|$) ]]; then
      emit_block "\`cp\` into \`/opt/<project>/current\` or \`/opt/<project>/releases\` is blocked by Deploy Standard v1 (CAPA-9 / CAPA-13 prevention). Filesystem-copy deploys bypass the git-clone source-of-truth and cause drift. Use \`deploy <project> <env>\` instead. See the \`deploy-standard\` skill."
    fi

    # --- Block: mv/rsync into /opt/<project>/current or /releases ---
    if [[ "$COMMAND" =~ (^|[^a-zA-Z0-9_])(mv|rsync)[[:space:]]+.*[[:space:]]+/opt/[^[:space:]]+/(current|releases)(/|[[:space:]]|$) ]]; then
      emit_block "Moving or rsyncing files into \`/opt/<project>/current\` or \`/releases\` is blocked by Deploy Standard v1. Commit to the repo and run \`deploy <project> <env>\`. See the \`deploy-standard\` skill."
    fi

    # --- Block: docker compose up outside a release directory ---
    # Match `docker compose up` or `docker-compose up` (legacy)
    if [[ "$COMMAND" =~ docker[[:space:]]+compose[[:space:]]+.*up ]] || \
       [[ "$COMMAND" =~ docker-compose[[:space:]]+.*up ]]; then
      # Allow if the command explicitly runs from /opt/*/current
      # (e.g. `cd /opt/treehouse/current && docker compose up -d --wait`)
      if [[ "$COMMAND" =~ /opt/[^[:space:]]+/current ]]; then
        allow
      fi
      emit_block "Direct \`docker compose up\` outside the deploy tool is blocked by Deploy Standard v1. The deploy tool handles image build, pre-swap health probe, atomic symlink swap, systemd restart, and rollback. Use \`deploy <project> <env>\` instead. If you are writing the \`deploy\` CLI itself or running a test harness, set \`DEPLOY_RUNNING=1\` in the command to bypass. See the \`deploy-standard\` skill."
    fi

    # --- Block: systemctl enable/start on */-prod|-staging.service written by hand ---
    # (Paranoid — deploy init handles systemctl enable; agent shouldn't run it.)
    # We only block `systemctl enable` with a hand-typed unit file path (file ends in .service
    # and lives under a path the agent might have written). Soft rule — don't over-block.

    allow
    ;;

  *)
    allow
    ;;
esac
